# Display message to the screen
print("welcome to qa406")
print("In week 1 i will learn")
print("")
print("how to use git and github")
print("how to output to the screen")
print("how to get user input")
print("")
print("I hope you enjoy the lesson thus far")
# Display escape characters
print("\n Displays a new line")
print("\t Displays a tab space")
print("\\ Displays a back slash")
print("\" Displays a double quote")
print("\' Displays a single quote")
print("First line \nSecond lane")
print("Before the tab \tAfter the tab")
print(" \n ")
print(" \t \"I am programming!\" ")